name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Promeni na svoj glavni branch ako nije 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout koda iz repozitorijuma
      - name: Checkout repository
        uses: actions/checkout@v3

      # Postavljanje Node.js okruženja
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Možeš promeniti verziju Node.js po potrebi

      # Instalacija zavisnosti React aplikacije
      - name: Install dependencies
        run: npm install

      # Bildovanje React aplikacije za produkciju
      - name: Build React App
        run: npm run build
        env:
          PUBLIC_URL: "/sleppy-baby-sounds/"  # Postavi base URL za GitHub Pages

      # Izlistavanje sadržaja build foldera nakon build-a
      - name: List build folder contents
        run: ls -laR dist/

      # Deploy na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Folder gde se nalazi build-ovana React aplikacija
          publish_branch: gh-pages  # Branch za GitHub Pages
